---
###############################################################################
# File
###############################################################################
# Test file existence and permissions.
#
# Args:
#   test_name: str - Test base name.
#   test_file: str - Path to remote file to test.
#   test_owner: str - File owner (UID or username).
#   test_group: str - File group (GID or groupname).
#   test_mode: str - File permissions (octal or permission string).
#   test_state: str - File state to test.
#   test_diff: bool - Display file diff on failure? Default: False.

- name: '{{ test_name }} | check requirements'  # noqa name[template]
  ansible.builtin.assert:
    quiet: true
    that:
      - test_name | length > 0
      - test_file | length > 0
      - test_owner | length > 0
      - test_group | length > 0
      - test_mode | length > 0
      - test_state | length > 0
    fail_msg: |
      tests.file requires:

      test_name: '{{ test_name }}'
      test_file: '{{ test_file }}'
      test_owner: '{{ test_owner }}'
      test_group: '{{ test_group }}'
      test_mode: '{{ test_mode }}'
      test_state: '{{ test_state }}'

- name: '{{ test_name }} | query'  # noqa name[template]
  ansible.builtin.file:
    path: '{{ test_file }}'
    owner: '{{ test_owner }}'
    group: '{{ test_group }}'
    mode: '{{ test_mode }}'
    state: '{{ test_state }}'
  check_mode: true
  diff: '{{ test_diff | default(false) }}'
  register: _tests_result

- name: '{{ test_name }} | assert'  # noqa name[template]
  ansible.builtin.assert:
    quiet: true
    that:
      - not _tests_result.changed
    fail_msg: |

      âœ˜ TEST FAILED.

      {{ test_file }} should exist with correct permissions.
